/**
 * Per-artifact AI summarizer + 48h scheduler.
 *
 * The full content of a Library artifact can be hundreds or thousands of
 * tokens. As the founder's library grows, sending the full body of every
 * `search_artifacts` hit to the chat model would "choke" the context window.
 *
 * The fix: keep a compact, AI-generated 2-3 sentence `summary` on each
 * artifact record. The `search_artifacts` tool result returns the summary
 * instead of the body; the model can call a separate `fetch_artifact` tool
 * if it really needs the full text.
 *
 * The summary is generated by the user's *own* configured provider/model
 * (same one they use for chat), so the cost is on them and the privacy story
 * is the same as a normal chat turn. Browser AI is intentionally NOT used —
 * the user explicitly asked for "the same AI API" so summaries have
 * consistent voice across runs.
 *
 * Refresh cadence: every 48 hours, OR sooner if the artifact was edited
 * after the last summary (cheaper than re-prompting on every change).
 *
 * Concurrency: a per-id lock prevents two summarizers fighting over the
 * same record; a global in-flight cap prevents stampeding the API.
 */

import { generateText } from 'ai'
import { db, type Artifact, type ArtifactType } from './db'
import { getModel, type ProviderId } from './providers'

/** How long a summary is considered fresh. */
export const SUMMARY_TTL_MS = 48 * 60 * 60 * 1000

/** Max in-flight summarizations at once. */
const MAX_INFLIGHT = 3

/** Per-artifact lock to prevent two runs from racing on the same id. */
const inFlight = new Set<string>()

/** Optional observer for the UI (e.g. "summarizing 2/7" badge). */
export type SummaryObserver = (state: {
  /** Number of artifacts with a stale or missing summary. */
  staleCount: number
  /** IDs currently being summarized. */
  inFlight: string[]
  /** Last successful summary timestamp. */
  lastSuccessAt?: number
  /** Last error (string) for debugging. */
  lastError?: string
}) => void

const observers = new Set<SummaryObserver>()
let lastSuccessAt: number | undefined
let lastError: string | undefined

function notify() {
  if (observers.size === 0) return
  void (async () => {
    const staleCount = await countStale()
    const state = {
      staleCount,
      inFlight: Array.from(inFlight),
      lastSuccessAt,
      lastError,
    }
    for (const o of observers) {
      try {
        o(state)
      } catch {
        // never let a buggy observer take down the scheduler
      }
    }
  })()
}

export function onSummaryStateChange(observer: SummaryObserver): () => void {
  observers.add(observer)
  notify()
  return () => {
    observers.delete(observer)
  }
}

/**
 * Build a compact 2-3 sentence summary of an artifact using a fast, cheap
 * model. Returns the summary string, or `null` if the call fails / no key.
 */
export async function summarizeArtifactText(artifact: Artifact): Promise<string | null> {
  const settings = await db.settings.get('singleton')
  if (!settings) return null
  const provider = settings.defaultProvider as ProviderId
  // Browser AI is intentionally not used here: the user asked for the
  // configured model so the same voice/cost/privacy story applies.
  if (!provider || provider === 'browser-ai') return null
  const modelId = settings.defaultModel
  if (!modelId) return null

  let model: any
  try {
    model = await getModel(provider, modelId)
  } catch (e: any) {
    lastError = e?.message || String(e)
    return null
  }

  const prompt = buildSummaryPrompt(artifact)
  try {
    const { text } = await generateText({
      model,
      prompt,
      // Compact request — keep temperature low, no streaming, no tools.
      temperature: 0.2,
      maxRetries: 1,
      abortSignal: AbortSignal.timeout(20_000),
    })
    return cleanSummary(text)
  } catch (e: any) {
    lastError = e?.message || String(e)
    return null
  }
}

function buildSummaryPrompt(a: Artifact): string {
  // Strip markdown and trim so we stay under the 8k prompt budget even for
  // 5k-token artifacts. The summary itself must fit in 400 chars.
  const stripped = (a.content || '')
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/[#*_`>~|-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim()
    .slice(0, 4000)
  return [
    'Summarise the following founder artifact in EXACTLY 2-3 sentences (max 400 characters).',
    'Focus on: (1) what it is, (2) the key decisions / numbers / facts,',
    '(3) why it matters to the founder\'s business.',
    'Output ONLY the summary — no preamble, no labels, no quotes, no markdown.',
    '',
    `TYPE: ${a.type}`,
    `TITLE: ${a.title}`,
    `TAGS: ${(a.tags || []).join(', ') || 'none'}`,
    '',
    'CONTENT:',
    stripped,
  ].join('\n')
}

function cleanSummary(text: string): string | null {
  if (!text) return null
  // Strip code fences, leading labels, and whitespace
  const stripped = text
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/^[\s\S]*?(?=.{20})/, '') // drop any prefix that's not part of the summary
    .replace(/^(summary|here.{0,10}summary|output)\s*[:：-]?\s*/i, '')
    .replace(/^["'`*_]+|["'`*_]+$/g, '')
    .replace(/\s+/g, ' ')
    .trim()
  if (stripped.length < 10) return null
  return stripped.length > 500 ? stripped.slice(0, 497).trimEnd() + '…' : stripped
}

/** Find artifacts whose summary is missing, stale (>48h), or stale relative to updatedAt. */
export async function findStaleArtifactIds(): Promise<string[]> {
  const all = await db.artifacts.toArray()
  const now = Date.now()
  const stale: string[] = []
  for (const a of all) {
    if (!a.content || a.content.length < 200) continue
    const needs = !a.summary || !a.summaryUpdatedAt
    const aged = a.summaryUpdatedAt && now - a.summaryUpdatedAt > SUMMARY_TTL_MS
    const edited = a.summaryUpdatedAt && a.updatedAt > a.summaryUpdatedAt
    if (needs || aged || edited) stale.push(a.id)
  }
  return stale
}

export async function countStale(): Promise<number> {
  return (await findStaleArtifactIds()).length
}

/**
 * Re-summarize a single artifact. Idempotent: writes summary + summaryUpdatedAt
 * only on success. Returns the new summary, or `null` if nothing changed.
 */
export async function reSummarizeArtifact(id: string): Promise<string | null> {
  if (inFlight.has(id)) return null
  if (inFlight.size >= MAX_INFLIGHT) return null
  inFlight.add(id)
  notify()
  try {
    const artifact = await db.artifacts.get(id)
    if (!artifact) return null
    // Skip very short artifacts — the body itself is already a summary.
    if (!artifact.content || artifact.content.length < 200) return artifact.summary || null
    const summary = await summarizeArtifactText(artifact)
    if (!summary) return null
    const now = Date.now()
    await db.artifacts.update(id, { summary, summaryUpdatedAt: now })
    lastSuccessAt = now
    lastError = undefined
    return summary
  } finally {
    inFlight.delete(id)
    notify()
  }
}

/**
 * Re-summarize every stale artifact, one at a time, in id order. Stops
 * cleanly if the page is hidden or the user aborts. Safe to call repeatedly.
 */
export async function runSummarizerSweep(opts: { signal?: AbortSignal } = {}): Promise<{
  total: number
  succeeded: number
  failed: number
  skipped: number
}> {
  const ids = await findStaleArtifactIds()
  if (ids.length === 0) return { total: 0, succeeded: 0, failed: 0, skipped: 0 }
  let succeeded = 0
  let failed = 0
  let skipped = 0
  for (const id of ids) {
    if (opts.signal?.aborted) break
    if (inFlight.has(id) || inFlight.size >= MAX_INFLIGHT) {
      skipped++
      continue
    }
    const out = await reSummarizeArtifact(id)
    if (out) succeeded++
    else failed++
  }
  return { total: ids.length, succeeded, failed, skipped }
}

// ---------------------------------------------------------------------------
// Background scheduler. Started on app boot, runs a sweep on a low-frequency
// interval while the app is open. Idempotent — calling startArtifactSummarizer
// twice is fine.
// ---------------------------------------------------------------------------

let schedulerStarted = false
let sweepTimer: ReturnType<typeof setTimeout> | null = null
const SWEEP_INTERVAL_MS = 5 * 60 * 1000 // 5 minutes

export function isSummarizerRunning(): boolean {
  return schedulerStarted
}

export function startArtifactSummarizer(): void {
  if (schedulerStarted) return
  schedulerStarted = true
  const run = async () => {
    try {
      await runSummarizerSweep()
    } catch (e: any) {
      lastError = e?.message || String(e)
    } finally {
      notify()
      schedule()
    }
  }
  const schedule = () => {
    if (!schedulerStarted) return
    if (sweepTimer) clearTimeout(sweepTimer)
    sweepTimer = setTimeout(run, SWEEP_INTERVAL_MS)
  }
  // Kick off after a short delay so the boot path isn't slowed down
  if (typeof window !== 'undefined') {
    // First sweep after 8s — give the app a moment to settle
    sweepTimer = setTimeout(run, 8_000)
    // And another after 60s — in case there were a lot to do on first open
    setTimeout(() => {
      if (schedulerStarted) run()
    }, 60_000)
  } else {
    run()
  }
}

export function stopArtifactSummarizer(): void {
  schedulerStarted = false
  if (sweepTimer) {
    clearTimeout(sweepTimer)
    sweepTimer = null
  }
}

/**
 * Force a re-summarize on the next sweep tick. Useful after a user edits
 * an artifact — we want the summary to reflect the new content, but we
 * don't want to block the UI on the AI call.
 */
export async function invalidateArtifactSummary(id: string): Promise<void> {
  await db.artifacts.update(id, { summaryUpdatedAt: 0 })
  notify()
}

/** Human-readable artifact type label (used in the summary prompt and UI). */
export const ARTIFACT_TYPE_LABEL: Record<ArtifactType, string> = {
  strategy: 'Strategy',
  plan90: '90-day plan',
  landing: 'Landing page copy',
  pricing: 'Pricing model',
  pitch: 'Pitch / story',
  review: 'Weekly review',
  teardown: 'Competitive teardown',
  investor: 'Investor update',
  custom: 'Custom document',
}
