/**
 * Artifact system: types, generators, parsing.
 * Artifacts are saved markdown documents generated by agents.
 */

import type { ArtifactType } from './db'

export interface ArtifactTemplate {
  type: ArtifactType
  name: string
  description: string
  emoji: string
  defaultTitle: string
  // Prompt to feed the agent when generating this artifact
  prompt: string
  // Markdown skeleton for the artifact (used for the structure preview while streaming)
  skeleton: string
}

export const ARTIFACT_TEMPLATES: Record<ArtifactType, ArtifactTemplate> = {
  strategy: {
    type: 'strategy',
    name: 'Strategy doc',
    description: 'A long-form strategy document covering positioning, ICP, value prop, GTM, and 12-month bets.',
    emoji: '🧭',
    defaultTitle: 'Strategy',
    prompt:
      'Write a comprehensive strategy document for my business. Cover: positioning (who for, what, why now, why us), value proposition, ideal customer profile, top 3 distribution channels, top 3 risks, and 3 bets for the next 12 months. Be specific. No fluff.',
    skeleton: `# Strategy

## Positioning
[who it's for, what it is, why now, why us]

## Ideal customer
[ICP description]

## Value proposition
[3-4 sentence value prop]

## Distribution
- [channel 1]
- [channel 2]
- [channel 3]

## Risks
- [risk 1]
- [risk 2]
- [risk 3]

## 12-month bets
- [bet 1]
- [bet 2]
- [bet 3]
`,
  },
  plan90: {
    type: 'plan90',
    name: '90-day plan',
    description: 'A quarterly plan broken into weeks, with the single most important outcome per week.',
    emoji: '📅',
    defaultTitle: '90-day plan',
    prompt:
      'Write a 90-day plan for my business, broken into 12 weeks. For each week, name the single most important outcome (not a list of tasks). At the end, add a "definition of done" for the quarter — what does success look like in 90 days?',
    skeleton: `# 90-day plan

**Definition of done:**
[what success looks like in 90 days]

## Week 1
- [outcome]

## Week 2
- [outcome]

…(through week 12)
`,
  },
  landing: {
    type: 'landing',
    name: 'Landing page copy',
    description: 'Headline, subhead, 3 benefits, social proof placeholder, and CTAs.',
    emoji: '✍️',
    defaultTitle: 'Landing page',
    prompt:
      'Write landing page copy for my business. Include: a hero (headline + subhead), 3 benefit blocks with a heading and 2-sentence description, a "How it works" section with 3 steps, a FAQ with 4 questions, and the final CTA. Be specific to my ICP. Avoid generic copy.',
    skeleton: `# [Headline]

[Subhead]

## Why us
- **[Benefit 1]**: [description]
- **[Benefit 2]**: [description]
- **[Benefit 3]**: [description]

## How it works
1. [Step 1]
2. [Step 2]
3. [Step 3]

## FAQ
- **Q:** [question] — A: [answer]
- …

## [CTA]
[button text]
`,
  },
  pricing: {
    type: 'pricing',
    name: 'Pricing model',
    description: 'Pricing tiers, rationale, and a unit economics sanity check.',
    emoji: '💵',
    defaultTitle: 'Pricing',
    prompt:
      'Design a pricing model for my business. Include: 2-3 tiers (Free / Pro / Team or similar), price points with a 1-line rationale each, what is/isn\'t included at each tier, an "anchor" tier (the one you want most people to pick), and a sanity check on unit economics (rough CAC, rough LTV, payback).',
    skeleton: `# Pricing

## Tier 1: [Name] — $[X]/mo
[What's included]

## Tier 2: [Name] — $[Y]/mo (anchor)
[What's included]

## Tier 3: [Name] — $[Z]/mo
[What's included]

## Why these prices
[1-2 paragraphs]

## Unit economics sanity check
- Rough CAC: $[X]
- Rough LTV: $[Y]
- Payback: [N] months
`,
  },
  pitch: {
    type: 'pitch',
    name: 'Pitch outline',
    description: 'A 5-minute narrative pitch — story, problem, solution, traction, ask.',
    emoji: '🎤',
    defaultTitle: 'Pitch',
    prompt:
      'Write a 5-minute pitch outline for my business. Follow this structure: (1) Hook — 1 sentence story; (2) Problem — what is broken and for whom; (3) Solution — what we built, in plain language; (4) Why now — why this is possible today; (5) Traction — what we\'ve seen; (6) Ask — what we need. Keep it under 600 words total.',
    skeleton: `# Pitch

## Hook
[1-sentence story]

## Problem
[what's broken, for whom]

## Solution
[what we built]

## Why now
[why this is possible today]

## Traction
[what we've seen]

## Ask
[what we need]
`,
  },
  review: {
    type: 'review',
    name: 'Weekly review',
    description: 'A Friday review of what shipped, what didn\'t, and what changes next week.',
    emoji: '🔁',
    defaultTitle: 'Weekly review',
    prompt:
      'Help me do a weekly review. Based on our conversation this week, write: (1) What I said I\'d do, (2) What actually happened, (3) What I learned, (4) What changes next week. Be honest with me — surface the gap between intent and action.',
    skeleton: `# Weekly review

## What I said I'd do
- [item]

## What actually happened
- [item]

## What I learned
- [insight]

## What changes next week
- [change]
`,
  },
  teardown: {
    type: 'teardown',
    name: 'Competitive teardown',
    description: 'A teardown of the top 3 competitors — what they do, where they win, where they lose.',
    emoji: '🔬',
    defaultTitle: 'Competitor teardown',
    prompt:
      'Do a competitive teardown. Identify the top 3 competitors in my space (or close adjacencies). For each, summarise: what they do, who they\'re for, where they win, where they lose or are vulnerable, and what we can learn. Use the web search tool for current info.',
    skeleton: `# Competitive teardown

## Competitor 1
- What they do:
- Who it's for:
- Where they win:
- Where they're vulnerable:
- What we learn:

## Competitor 2
…

## Competitor 3
…

## Our wedge
[the gap we can own]
`,
  },
  investor: {
    type: 'investor',
    name: 'Investor update',
    description: 'A monthly investor update — numbers, progress, asks.',
    emoji: '💼',
    defaultTitle: 'Investor update',
    prompt:
      'Write a monthly investor update for my business. Sections: (1) TL;DR — 2 sentences; (2) Key numbers — MRR, users, growth, runway; (3) Progress — what we shipped; (4) Setbacks — what didn\'t work; (5) Asks — specific introductions or help needed.',
    skeleton: `# Investor update — [Month YYYY]

**TL;DR:** [2 sentences]

## Numbers
- MRR: $[X] (+[Y]% MoM)
- Users: [N] (+[M]% MoM)
- Runway: [N] months

## Progress
- [shipped thing]

## Setbacks
- [didn't work]

## Asks
- [specific intro / help]
`,
  },
  custom: {
    type: 'custom',
    name: 'Custom artifact',
    description: 'A custom markdown document the user requested.',
    emoji: '📄',
    defaultTitle: 'Custom artifact',
    prompt: '',
    skeleton: `# [Title]

[content]
`,
  },
}

export const ARTIFACT_LIST = Object.values(ARTIFACT_TEMPLATES)

/**
 * Parse a chat message to extract artifact blocks.
 * Format: <artifact type="TYPE" title="TITLE">\n...\n</artifact>
 */
export interface ParsedArtifact {
  type: ArtifactType
  title: string
  content: string
  startIndex: number
  endIndex: number
}

const ARTIFACT_RE = /<artifact\s+type="([a-z0-9_-]+)"(?:\s+title="([^"]*)")?\s*>([\s\S]*?)<\/artifact>/g

export function parseArtifacts(text: string): ParsedArtifact[] {
  const out: ParsedArtifact[] = []
  let m: RegExpExecArray | null
  ARTIFACT_RE.lastIndex = 0
  while ((m = ARTIFACT_RE.exec(text)) !== null) {
    const rawType = m[1]
    const title = m[2] || ARTIFACT_TEMPLATES[rawType as ArtifactType]?.defaultTitle || 'Artifact'
    const type = (ARTIFACT_TEMPLATES[rawType as ArtifactType] ? rawType : 'custom') as ArtifactType
    out.push({
      type,
      title,
      content: m[3].trim(),
      startIndex: m.index,
      endIndex: m.index + m[0].length,
    })
  }
  return out
}

/** Strip artifact blocks from a chat message for display. */
export function stripArtifacts(text: string): string {
  return text.replace(ARTIFACT_RE, '').replace(/\n{3,}/g, '\n\n').trim()
}

// ---------------------------------------------------------------------------
// HTML preview blocks
// ---------------------------------------------------------------------------
// Detects ```html ... ``` fenced code blocks in chat text. The model is
// instructed to wrap any HTML mockup / design in this exact format. We render
// it in a sandboxed iframe so the founder can see (and interact with) the
// visual the agent produced, right inside the conversation.

export interface ParsedHtmlBlock {
  /** Raw HTML to render in the iframe (srcdoc) */
  html: string
  /** Language tag after the fence — only "html" / "htm" are accepted, default html */
  lang?: string
  /** Optional one-line context the model wrote just before the fence */
  context?: string
  startIndex: number
  endIndex: number
  /** True if the closing ``` hasn't streamed in yet (live preview) */
  partial: boolean
}

// Match BOTH complete ```html ... ``` blocks AND a still-open ```html ... stream
// (so the preview can render in real-time as the model types).
const HTML_BLOCK_OPEN = /```(html|htm)\b([^\n]*)\n?/i
const HTML_BLOCK_FULL = /```(html|htm)\b([^\n]*)\n([\s\S]*?)```/g
const HTML_BLOCK_PARTIAL = /```(html|htm)\b([^\n]*)\n([\s\S]*)$/i

export function parseHtmlBlocks(text: string): ParsedHtmlBlock[] {
  const out: ParsedHtmlBlock[] = []
  // First pass: collect all complete blocks
  const taken = new Set<number>()
  let m: RegExpExecArray | null
  HTML_BLOCK_FULL.lastIndex = 0
  while ((m = HTML_BLOCK_FULL.exec(text)) !== null) {
    const lang = m[1]
    const contextLine = m[2]?.trim() || undefined
    const html = m[3]
    out.push({
      html,
      lang,
      context: contextLine,
      startIndex: m.index,
      endIndex: m.index + m[0].length,
      partial: false,
    })
    // Mark the matched range as taken
    for (let i = m.index; i < m.index + m[0].length; i++) taken.add(i)
  }
  // Second pass: if a ```html opener is present without a closing fence, add
  // it as a partial block so the preview can update as the model streams.
  const partialMatch = HTML_BLOCK_PARTIAL.exec(text)
  if (partialMatch) {
    const idx = partialMatch.index
    let overlaps = false
    for (const takenIdx of taken) {
      if (Math.abs(takenIdx - idx) < 10) {
        overlaps = true
        break
      }
    }
    if (!overlaps) {
      out.push({
        html: partialMatch[3] || '',
        lang: partialMatch[1],
        context: partialMatch[2]?.trim() || undefined,
        startIndex: idx,
        endIndex: text.length,
        partial: true,
      })
    }
  }
  // Sort by start position so the UI renders them in document order
  out.sort((a, b) => a.startIndex - b.startIndex)
  return out
}

/** Strip ```html ... ``` blocks from a chat message for display. */
export function stripHtmlBlocks(text: string): string {
  return text
    .replace(HTML_BLOCK_FULL, '')
    .replace(HTML_BLOCK_OPEN, '')
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/** Quick check — does the text contain anything that looks like an HTML block? */
export function hasHtmlBlock(text: string): boolean {
  return /```(html|htm)\b/i.test(text)
}
